
replicaCount: 1

image:
  repository: jfrog.it-academy.by/public/jenkins-ci
  pullPolicy: IfNotPresent
  tag: "shahov"
ingress:
  enabled: enabled
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: "jenkins-helm.k8s-32.sa"
  hosts:
    - host: jenkins-helm.k8s-31.sa
      paths:
        - path: /
          pathType: ImplementationSpecific
      volumes:
        - name: jenkins-auth-config
          configMap:
            name: basic-security
        - name: jenkins-config-yaml
          configMap:
            name: jenkins-config
        - name: jenkins-config
          nfs:
            server: 192.168.37.105
            path: /mnt/IT-Academy/nfs-data/sa2-21-22/Shahov/jenkins

resources:
  limits:
    cpu: 2000m
    memory: 2000Mi
  requests:
    cpu: 2000m
    memory: 3000Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
